In [6]:
import numpy as np

a = np.zeros((5, 1))
print(f'a = {a}, a.shape = {a.shape}')

b = np.zeros((1, 5))
print(f'b = {b}, b.shape = {b.shape}')

# User specified values:
c = np.array([
    [1], 
    [2], 
    [3]])

print(f'c = {c}, c.shape = {c.shape}')

a = [[0.]
 [0.]
 [0.]
 [0.]
 [0.]], a.shape = (5, 1)
b = [[0. 0. 0. 0. 0.]], b.shape = (1, 5)
c = [[1]
 [2]
 [3]], c.shape = (3, 1)


In [17]:
# Operations on matrices

# reshape is a convenient way to create matrices
a = np.arange(10).reshape(-1, 2)
print(f'a = {a}, a.shape = {a.shape}')

a = [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]], a.shape = (5, 2)


**Reshape**  
The previous example used [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) to shape the array.  
`a = np.arange(6).reshape(-1, 2) `   
This line of code first created a *1-D Vector* of six elements. It then reshaped that vector into a *2-D* array using the reshape command. This could have been written:  
`a = np.arange(6).reshape(3, 2) `  
To arrive at the same 3 row, 2 column array.
The -1 argument tells the routine to compute the number of rows given the size of the array and the number of columns.

In [19]:
# Access an element:

print(f'a[0, 1] = {a[0, 1]}')
print(f'a[1, 1] = {a[1, 1]}')
print(f'a[3, 0] = {a[3, 0]}')
print(f'a[4, 1] = {a[4, 1]}')

a[0, 1] = 1
a[1, 1] = 3
a[3, 0] = 6
a[4, 1] = 9


In [34]:
# Slicing in matrices

a = np.arange(20).reshape(-1, 5)
print(f'a = {a}, a.shape = {a.shape}')

# Print 2 elements after the 1st index of the 2nd row
print(f'a[1, 1:3:1] = {a[1, 1:3:1]}, shape = {a[1, 1:3:1].shape}')


# Do the same, but for 3 consecutive rows:
print(f'a[0:3:1, 1:3:1] = {a[0:3:1, 1:3:1]}, shape = {a[0:3:1, 1:3:1].shape}')

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# Access first row elements:
print(f'a[1] = {a[1]}, shape = {a[1].shape}')

# Access last four elements of the last row
print(f'a[-1, -4:] = {a[-1, -4:]}')

a = [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]], a.shape = (4, 5)
a[1, 1:3:1] = [6 7], shape = (2,)
a[0:3:1, 1:3:1] = [[ 1  2]
 [ 6  7]
 [11 12]], shape = (3, 2)
a[:,:] = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] ,  a[:,:].shape = (4, 5)
a[1] = [5 6 7 8 9], shape = (5,)
a[-1, -4:] = [16 17 18 19]
